### ISSUE TITLE
Create the pre-built binary for the plugin

### ISSUE THREAD

**Issue by RyanSiu1995** [kyma-incubator/terraform-provider-kind#16]
Thank you for the development!
I would like to take this into our testing enivronment but I could not find the release here.
Could you mind to have the release binary for easy installation?

**Comment by tehcyx** [comment]
Hey @RyanSiu1995 
I'm about to create a release but am just waiting for #15 to be merged first.

**Comment by RyanSiu1995** [comment]
Could you mind that I could open up a PR to use GitHub Action to build the release based on Tag?

**Comment by tehcyx** [comment]
At this point we don't think there's a big benefit to using GitHub Actions for releases. I've just released version v0.0.1, please feel free to use that in your testing environment: https://github.com/kyma-incubator/terraform-provider-kind/releases/tag/v0.0.1
