### ISSUE TITLE
Image loading with terraform

### ISSUE THREAD

**Issue by RyanSiu1995** [kyma-incubator/terraform-provider-kind#17]
It will be awesome if this plugin could support this command.
```
kind load docker-image my-custom-image:unique-tag
```

**Comment by a-thaler** [comment]
Hi @RyanSiu1995, 

can you maybe give a proposal on how exactly you can specify the image in the terraform manifest and explain the expected effect. Then maybe someone interested can pick that topic up and bring forward. The kyma team currently has no capacity to implement it.

**Comment by tehcyx** [comment]
Hey @RyanSiu1995, 

What is your goal with this? Personally I see the use of `kind load docker-image ...` more as a development step, which is repeated multiple times as you develop the custom image and applied to the same cluster over and over.
Are you trying to avoid using the kind CLI to load images into the cluster? For the custom images you would still need to run terraform to apply the changes.

Happy to hear your thoughts on this and maybe a proposal along with how this could be implemented.

Cheers,
Daniel

**Comment by RyanSiu1995** [comment]
Hey @tehcyx and @a-thaler,
thank you for the prompt reply!
My use case is super simple. We want to either load the image on the node or pass the docker credential to all nodes with terraform. This automation in my scenario is to setup the environment for integration tests.
Loading an image on the nodes is the case for local integration tests in my use case.
So, the terraform resources will like this.
```
resource "kind_container_images" "images" {
  name = "image-name"
  cluster-name = "cluster-name"
  # Optional fields
  target-nodes = "worker1,worker2"
}
```

Another potential feature will be to load the current docker profile into each node. In the documentation of kind, we actually need to do this with a script. It will be awesome if we could do the same stuff with terraform. Especially we want to pull the images from a private repository.
```
resource "kind_docker_credential" "credential" {
  # If nothing is given, it will by default copy the current docker profile
  # Optional
  username = ""
  password = ""
  registry = ""
  # etc....
}
```

Please let me know if you have any questions!

**Comment by tehcyx** [comment]
Hi @RyanSiu1995, 
We recently added the option to specify that the provider should only report the cluster created when kind reports back that the cluster is ready: https://github.com/kyma-incubator/terraform-provider-kind/blob/master/kind/resource_cluster.go#L109-L112

We noticed the problem with this is, kind will only report on the control-plane to be ready not so for the worker nodes. In this case unless we create checks that use the kubernetes API and wait for workers to be ready as well, I don't know this is possibly at this point. How do you solve this problem currently using kind without the provider if at all?

**Comment by tehcyx** [comment]
Not sure where to take this at this time with the limitations mentioned. Please feel free to reopen this, if you think I missed something, but I don't think this is currently possible with tools built-in to kind.
