### ISSUE TITLE
terraform init error

### ISSUE THREAD

**Issue by packyzbq** [kyma-incubator/terraform-provider-kind#29]
Hi, I follow the instructions in the README. After running `terraform init`, an error occurs:
```
[root@k8s1 terraform]# terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/kind...

Error: Failed to install provider

Error while installing hashicorp/kind: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/kind
```
Anything else shoud I do to configure terraform?

**Comment by tehcyx** [comment]
Hi @packyzbq ,

We're currently looking to publish the provider to the registry. See #23 for reference.

As long as this is not done you'll have to build the provider yourself or download the binary from the [releases](https://github.com/kyma-incubator/terraform-provider-kind/releases) and put it in the right place for terraform to pick it up. Please note that the current master branch has some changes that are not in a release yet, but the next release should also be the one that will be on the registry.

The right folder for your system is described in terraforms documentation: https://www.terraform.io/docs/plugins/basics.html#installing-plugins
> Third-party plugins (both providers and provisioners) can be manually installed into the user plugins directory, located at %APPDATA%\terraform.d\plugins on Windows and ~/.terraform.d/plugins on other systems.

**Comment by tehcyx** [comment]
The error should not occur anymore, since it is now published: https://registry.terraform.io/providers/kyma-incubator/kind/latest
