### ISSUE TITLE
Help for using kubeadm_config_patches !!!

### ISSUE THREAD

**Issue by maabik** [kyma-incubator/terraform-provider-kind#36]
Hi All !
How to use  kubeadm_config_patches on resource. I have tried this but not success.

            kubeadm_config_patches = [
                <<-INTF
                kind: InitConfiguration
                  nodeRegistration: 
                      kubeletExtraArgs: 
                          node-labels = "ingress-ready=true"
               INTF
This is what I have got:

$ terraform apply "kind.out"
kind_cluster.default: Creating...
kind_cluster.default: Still creating... [10s elapsed]

****Error: failed to generate kubeadm config content: failed to parse patches: failed to parse type meta for "kind: InitConfiguration\n  nodeRegistration: \n      kubeletExtraArgs: \n          node-labels = \"ingress-ready=true\"\n": error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context**
  on main.tf line 13, in resource "kind_cluster" "default":
  13: resource "kind_cluster" "default" {
            ]**

Any example ?  Please  help !  Thanks in advance

MAA-BIK

**Comment by tehcyx** [comment]
Hi @maabik , I'll have to try this myself, what I do notice is your indentation is wrong. In the first example here https://kind.sigs.k8s.io/docs/user/ingress/ the `nodeRegistration` piece has the same indentation as `kind`, but I believe the error is coming already before it gets to the yaml validation. Let me try this and get back to you.

**Comment by tehcyx** [comment]
Hi @maabik,

I'm able to spin up a cluster with this config:
```hcl
resource "kind_cluster" "test" {
  name = "test"
  wait_for_ready = true
  kind_config {
    kind = "Cluster"
    api_version = "kind.x-k8s.io/v1alpha4"

    node {
        role = "control-plane"
        kubeadm_config_patches = [
        <<-INTF
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-labels: "ingress-ready=true"
        INTF
        ]
    }
  }
}
```
It seems the indentation was the only problem. I'll close the issue but feel free to re-open if you're still encountering problems

**Comment by maabik** [comment]
@tehcyx 
Thanks a lot.You save me time.  It works
