### ISSUE TITLE
Cluster parameters not available as output

### ISSUE THREAD

**Issue by jnsvd** [kyma-incubator/terraform-provider-kind#39]
The `kind_cluster` resource doesn't have outputs that can be used by other modules to connect to the created cluster. The following state attributes should be exposed for other modules:
* `client_certificate`
* `client_key`
* `cluster_ca_certificate`
* `endpoint`
* `kubeconfig`

**Comment by tehcyx** [comment]
Hi @jnsvd,
I'll have a look at the issue in the coming days.

**Comment by jnsvd** [comment]
@tehcyx Turns out my IDE is not recognising the variable names of third-party providers, so nothing is wrong with the code. This issue can be closed.

**Comment by tehcyx** [comment]
@jnsvd thanks for reporting back. Glad you could solve it on your end.
