### ISSUE TITLE
Chagne container backend from docker to podman

### ISSUE THREAD

**Issue by PePoDev** [kyma-incubator/terraform-provider-kind#44]
Does this provider have the ability to change the container backend from docker to podman?

**Comment by tehcyx** [comment]
Hi @PePoDev,

I cannot find any documentation on how to spin up kind on podman other than an old [PR](https://github.com/kubernetes-sigs/kind/pull/1302) which indicates it could be done via environment variable: `KIND_EXPERIMENTAL_PROVIDER=podman`.

It might just work with setting this env variable. You could try it out and check if it works.

**Comment by PePoDev** [comment]
Thanks, But not working.

`kind` cli will interact with podman but `terraform` not

![image](https://user-images.githubusercontent.com/15852891/116192260-c68c2a00-a757-11eb-9bf0-673e6603e8cd.png)

**Comment by tehcyx** [comment]
terraform shouldn't be calling any docker native things. I would have to setup podman on my machine to check out if I can reproduce this.

**Comment by PePoDev** [comment]
It looks like Kind will detect Docker first when calling with API, not CLI

https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/provider.go#L114

**Comment by tehcyx** [comment]
Are you able to figure out (with podman commands) if a cluster is running even though kind is not returning it? And in that case, does the kubeconfig work to access the cluster?

I wonder if we need to set some flag when creating the cluster to make kind recognize it.

**Comment by PePoDev** [comment]
![image](https://user-images.githubusercontent.com/15852891/116350348-fb61b500-a81b-11eb-96bc-45b35a8a3a78.png)

I run this, But Kind creates a control plan container on Docker without any kubeconfig.

**Comment by tehcyx** [comment]
kind seems to not pick up the env variable in that case. I am missing the output here that you got before:
`using podman due to KIND_EXPERIMENTAL_PROVIDER`

If you're on the kubernetes slack you could check in the #kind channel or create an issue on https://github.com/kubernetes-sigs/kind/issues why the behavior is like that or what is done wrong in the steps.
