### ISSUE TITLE
nginx ingress is never reachable when using containerd_config_patches

### ISSUE THREAD

**Issue by nickjj** [kyma-incubator/terraform-provider-kind#47]
After following the docs and looking at a bit of your tests I came up with:

```terraform
resource "kind_cluster" "default" {
  name           = "example"
  wait_for_ready = true

  kind_config {
    kind        = "Cluster"
    api_version = "kind.x-k8s.io/v1alpha4"
    containerd_config_patches = [
      <<-TOML
      kind = "InitConfiguration"

      [nodeRegistration.kubeletExtraArgs]
      node-labels = "ingress-ready=true"
      TOML
    ]

    node {
      role = "control-plane"
      extra_port_mappings {
        container_port = 80
        host_port      = 80
      }
    }

    node {
      role = "worker"
    }
  }
}
```

After applying this, and applying kind's instructions for installing the nginx ingress at https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx it always results in getting an empty reply from the server when running `curl localhost`.

If I use kind's config file and the kind CLI tool instead of this provider it works and the nginx ingress is reachable.

It's worth pointing out that the `containerd_config_patches ` is applied to the control plane node in kind's config based on their documentation at https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster. I'm not sure if that applies here but in your provider it expects it to be set on the `kind_config` itself, not the control plane.

Also I converted kind's YAML to TOML using an online converter.

**Comment by tehcyx** [comment]
Hi @nickjj ,

It seems to me, that you have mixed some things up. You're using `containerd_config_patches` instead of `kubeadm_config_patches` which would be on the node level.

This has worked for me:
```hcl
resource "kind_cluster" "default" {
  name = "new-cluster"
  wait_for_ready = true

  kind_config {
    kind = "Cluster"
    api_version = "kind.x-k8s.io/v1alpha4"

    node {
      role = "control-plane"
      kubeadm_config_patches = [
        "kind: InitConfiguration\nnodeRegistration:\n  kubeletExtraArgs:\n    node-labels: \"ingress-ready=true\"\n"
      ]
      extra_port_mappings {
        container_port = 80
        host_port      = 80
      }
      extra_port_mappings {
        container_port = 443
        host_port      = 443
      }
    }

    node {
      role = "worker"
    }

    node {
      role = "worker"
    }
  }
}
```

Unfortunately the `kubeadm_config_patches` does not allow to pass toml and it has to be a string at this point.

Creating this cluster via `terraform apply` and then installing nginx via the described way in the kind docs: https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx

I can do this:
```bash
$ curl localhost
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

As for the extra port mappings, the field is not unique and you're allowed to repeat it, as shown above.

Let me know if that works for you.

**Comment by nickjj** [comment]
Good catch. It's working now.

For anyone else out there, here's a quick test you can perform to confirm it works, this is taken from kind's docs:

```sh
# Install the nginx ingress controller
kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml

# Wait until it's ready
kubectl wait --namespace ingress-nginx \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/component=controller \
  --timeout=90s

# Run a simple echo server
kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml

# Once all of that finishes you can do this and it should respond with "foo":
curl localhost/foo
```
