### ISSUE TITLE
[0.0.9] Does not work on Apple Silicon (M1 Pro)

### ISSUE THREAD

**Issue by gm2211** [kyma-incubator/terraform-provider-kind#50]
When I run `terraform init` I get ` Provider registry.terraform.io/kyma-incubator/kind v0.0.9 does not have a package available for your current platform, darwin_arm64.`.

(Partial) content of `versions.tf` for one of my modules:

```
terraform { 
   required_providers { 
     kind = { 
       source = "kyma-incubator/kind" 
       version = "0.0.9" 
     }
   }
}
```

**Comment by tehcyx** [comment]
Hi @gm2211,

I'll try to setup new build targets for darwin_arm64, but I will not be able to test that they work as I don't have an Apple Silicon machine. Let me read up on this and hopefully I can create a PR this weekend.

**Comment by rakesh-garimella** [comment]
Hi @gm2211 can you please give it a try with `v0.0.10`

**Comment by tehcyx** [comment]
@gm2211 @rakesh-garimella unfortunately `v0.0.10` skipped the arm64 build for darwin, even though the go version in the mod file is set to 1.16: https://goreleaser.com/deprecations/#builds-for-darwinarm64

I'll have to dig a little, to figure out why that happened.

**Comment by tehcyx** [comment]
@rakesh-garimella https://github.com/kyma-incubator/terraform-provider-kind/pull/52 should fix the problem, i'll cut another release after this.

**Comment by gm2211** [comment]
@tehcyx @rakesh-garimella Happy to test this once the new release is out

**Comment by tehcyx** [comment]
@gm2211 v0.0.11 is just finished and includes a darwin/arm64 binary. Could you try that out?

**Comment by gm2211** [comment]
Confirmed that `v0.0.11` works - thanks for the quick turn around!

<img width="578" alt="image" src="https://user-images.githubusercontent.com/1555460/140996969-fc97319e-45d4-4218-9077-ce57adbe794e.png">
