### ISSUE TITLE
How can I use kind command to connect with kind cluster

### ISSUE THREAD

**Issue by yuzp1996** [kyma-incubator/terraform-provider-kind#9]
Hello，I like this provider very much, It help me a lot. But I met some problem now. 

When I use terrafrom and this provider build a kind cluster, I can not use kind command to communicate with kind cluster.

 For example If I input  "kind get clusters", I will get nothing. But actually I have made a kind cluster with this provider.

Any suggestions?  Thank you very much

**Comment by tehcyx** [comment]
Hi @yuzp1996,
What are the *kind* version and *terraform* version you're using? I'm using *kind version 0.8.0*, *terraform 0.12.10* with the current provider from master and for the examples in the [README](https://github.com/kyma-incubator/terraform-provider-kind#usage) file the cluster shows up in the `kind get cluster` list.

Did you get any errors during creation? What does the output look like?

**Comment by tehcyx** [comment]
Closing due to missing information. Feel free to reopen or create a new issue if you still encounter this issue.
